### ISSUE TITLE
Unable to compile nota documents containing code blocks

### ISSUE THREAD

**Issue by aaronjeline** [nota-lang/nota#20]
I'm unable to compile any nota document containing highlighted code. (It works fine in the `nota edit` mode, but `nota build` fails.

Here's my nota document:

``````
%%%
import {rust} from "@codemirror/lang-rust"
%%%

@Title: Test

```rust
fn f() {
        println!("hello");
}
```
``````
Here's my `package.json`:
```json
{
        "dependencies" : {
                "@codemirror/lang-rust" : "^6.0.0"
        }
}
```

Error when running `nota build index.nota`:
```
[9:58:41 PM] info: Starting build...
[9:58:42 PM] info: Waiting for browser (may take ~15s the first build)...
[9:58:42 PM] info: Rendering page: index -> dist/index.html
[9:58:42 PM] info: (/index) JSHandle@error
[9:58:42 PM] info: Note: for better stack traces, try building with -g
[9:58:42 PM] error: (/index)Error: Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
    at s (http://localhost:8000//index.mjs:301:19292)
    at s (http://localhost:8000//index.mjs:301:18871)
    at s (http://localhost:8000//index.mjs:301:19470)
    at s (http://localhost:8000//index.mjs:301:18871)
    at s (http://localhost:8000//index.mjs:301:19470)
    at s (http://localhost:8000//index.mjs:301:18871)
    at Oj (http://localhost:8000//index.mjs:301:19485)
    at Zf.resolve (http://localhost:8000//index.mjs:301:18003)
    at Ze.create (http://localhost:8000//index.mjs:301:27063)
    at http://localhost:8000//index.mjs:306:52607
[9:58:44 PM] info: Cleaning up unused files...
[9:58:44 PM] info: Built in 2.20s.
```

(Anyway loving nota, very cool)

**Comment by willcrichton** [comment]
Thanks for filing this issue -- Nota is in low-maintenance mode right now while I work on the next big iteration of its design, but I will make sure to address this!
